### PR TITLE
Added click-on-the-interface controls to facilitate porting on mobile

### PR DESCRIPTION
**Pull request by alin256**
If you click on the machine you start/pause.
If you click elsewhere you toggle bias

Partially addresses #26

### CODE REVIEW

**Comment by alin256** [comment]
It works on iPad and iPhone apart from scaling

**Comment by alin256** [comment]
> slight bug with a pause when stuck

That actually copied it from the previous PR, should we same on the escape button. 
I think we should check the state for "STUCK".

**Comment by alin256** [comment]
> That actually copied it from the previous PR, should we same on the escape button.
> I think we should check the state for "STUCK".

Now start/stop behaviour is fixed regardless of the controls used: a GUI button, a keyboard key or a mouse click

**Review by alin256 — COMMENTED** [review]
return false;

deactivates GUI at least on the iPhone as it turns out. Need to fix

**Comment by alin256** [comment]
After some iterations, all new bugs and some old ones are fixed. I tested it on a computer and iOS. Can be tested here: 
https://al-digital.no/Directional-Boring

I will merge if there are no objections.

**Comment by alin256** [comment]
Added a bit more detailed stats to be used for scoring

**Comment by alin256** [comment]
Integrated @DenisovichDev 's pull request

**Comment by alin256** [comment]
I am going to get a second baby tomorrow, so need to push as is ;)

**Comment by shiffman** [comment]
Thank you @alin256, and congrats to you!!!!!

**Comment by DenisovichDev** [comment]
Congrats @alin256!

**Comment by ArztKlein** [comment]
Congratulations @alin256!!

**Comment by alin256** [comment]
Thank you very much @shiffman @DenisovichDev and @ArztKlein. We finally got a healthy and happy girl, and I can accept congratulations from this pull request :)

**Pull request merged**
